spring:
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true











